"""Initial migration

Revision ID: 6dcd817518d7
Revises: 
Create Date: 2024-11-01 20:24:10.886642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dcd817518d7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('demo_url',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('github_url',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('github_url',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('demo_url',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)

    # ### end Alembic commands ###
